In [473]:
# Now we are going to start to work with tensorflow
# and learn the fundamentals. Let's go!

### Introduction to Tensors

In [474]:
# libraries
import tensorflow as tf
print(tf.__version__)

2.15.0


In [475]:
# Creates a constant tensor from a tensor-like object.
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [476]:
# Get the number of dimension - Tensor
scalar.ndim

0

In [477]:
# Create a vector 
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [478]:
vector.ndim

1

In [479]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [480]:
matrix.ndim

2

In [481]:
matrix_constant = tf.constant([[1., 2.],
                 [3., 4.],
                 [5., 6.]])
matrix_constant.ndim

2

In [482]:
# Constant 1-D Tensor from a python list.
tensor = tf.constant([[[1, 2],[1, 2],
                      [1, 2],
                      [1, 2]]])
tensor

<tf.Tensor: shape=(1, 4, 2), dtype=int32, numpy=
array([[[1, 2],
        [1, 2],
        [1, 2],
        [1, 2]]], dtype=int32)>

In [483]:
tensor.ndim

3

In [484]:
# Create a scalar tensor
scalar_tensor = tf.constant(5)
print("Scalar tensor:")
print(scalar_tensor)

Scalar tensor:
tf.Tensor(5, shape=(), dtype=int32)


In [485]:
# Create a vector tensor
vector_tensor = tf.constant([1, 2, 3, 4, 5])
print("\nVector tensor:")
print(vector_tensor)


Vector tensor:
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [486]:
# Create a matrix tensor
matrix_tensor = tf.constant([[1, 2, 3],
                             [4, 5, 6]])
print("\nMatrix tensor:")
print(matrix_tensor)


Matrix tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [487]:
# Create a higher-dimensional tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]],
                         [[9, 10], [11, 12]]])
print("\n3D tensor:")
print(tensor_3d)


3D tensor:
tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)


In [488]:
tensor_3d.ndim

3

In [489]:
# Set the seed for reproducibility
tf.random.set_seed(42)

In [490]:
# Create a variable tensor
initial_value = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)
variable_tensor = tf.Variable(initial_value)

# Print the variable tensor
print("Variable tensor:")
print(variable_tensor)

Variable tensor:
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>


In [491]:
# Convert the TensorFlow Variable to a tensor
tensor = variable_tensor.read_value()

# Get the number of dimensions
ndim = tensor.ndim

# Print the number of dimensions
print("Number of dimensions:", ndim)

Number of dimensions: 2


In [492]:
not_shuffle = tf.constant([[10, 7], 
                           [2, 6],
                           [3, 9]])

In [499]:
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  6],
       [ 3,  9]], dtype=int32)>

In [494]:
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  6],
       [ 3,  9]], dtype=int32)>

In [513]:
# Set the seed for reproducibility
tf.random.set_seed(42)

If you set the seed for reproducibility using tf.random.set_seed(42), the random operations in TensorFlow, including shuffling, will produce the same results across different runs of the program as long as the operations are performed in the same order.

Here's how you can apply the seed to shuffle a tensor:

In [517]:
# Create a tensor
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Randomly shuffle the tensor along the first dimension
shuffled_tensor = tf.random.shuffle(tensor)

# Print the original and shuffled tensors
print("Original tensor:")
print(tensor)
print("\nShuffled tensor:")
print(shuffled_tensor)

Original tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

Shuffled tensor:
tf.Tensor(
[[7 8 9]
 [4 5 6]
 [1 2 3]], shape=(3, 3), dtype=int32)
