In [438]:
# Now we are going to start to work with tensorflow
# and learn the fundamentals. Let's go!

### Introduction to Tensors

In [439]:
# libraries
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp
print(tf.__version__)

2.15.0


In [440]:
# Creates a constant tensor from a tensor-like object.
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [441]:
# Get the number of dimension - Tensor
scalar.ndim

0

In [442]:
# Create a vector 
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [443]:
vector.ndim

1

In [444]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [445]:
matrix.ndim

2

In [446]:
matrix_constant = tf.constant([[1., 2.],
                 [3., 4.],
                 [5., 6.]])
matrix_constant.ndim

2

In [447]:
# Constant 1-D Tensor from a python list.
tensor = tf.constant([[[1, 2],[1, 2],
                      [1, 2],
                      [1, 2]]])
tensor

<tf.Tensor: shape=(1, 4, 2), dtype=int32, numpy=
array([[[1, 2],
        [1, 2],
        [1, 2],
        [1, 2]]], dtype=int32)>

In [448]:
tensor.ndim

3

In [449]:
# Create a scalar tensor
scalar_tensor = tf.constant(5)
print("Scalar tensor:")
print(scalar_tensor)

Scalar tensor:
tf.Tensor(5, shape=(), dtype=int32)


In [450]:
# Create a vector tensor
vector_tensor = tf.constant([1, 2, 3, 4, 5])
print("\nVector tensor:")
print(vector_tensor)


Vector tensor:
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [451]:
# Create a matrix tensor
matrix_tensor = tf.constant([[1, 2, 3],
                             [4, 5, 6]])
print("\nMatrix tensor:")
print(matrix_tensor)


Matrix tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [452]:
# Create a higher-dimensional tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]],
                         [[9, 10], [11, 12]]])
print("\n3D tensor:")
print(tensor_3d)


3D tensor:
tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)


In [453]:
tensor_3d.ndim

3

In [454]:
# Set the seed for reproducibility
tf.random.set_seed(42)

In [455]:
# Create a variable tensor
initial_value = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)
variable_tensor = tf.Variable(initial_value)

# Print the variable tensor
print("Variable tensor:")
print(variable_tensor)

Variable tensor:
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>


In [456]:
# Convert the TensorFlow Variable to a tensor
tensor = variable_tensor.read_value()

# Get the number of dimensions
ndim = tensor.ndim

# Print the number of dimensions
print("Number of dimensions:", ndim)

Number of dimensions: 2


In [457]:
not_shuffle = tf.constant([[10, 7], 
                           [2, 6],
                           [3, 9]])

In [458]:
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  6],
       [ 3,  9]], dtype=int32)>

In [459]:
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  6],
       [ 3,  9]], dtype=int32)>

In [460]:
# Set the seed for reproducibility
tf.random.set_seed(42) # global level random seed

If you set the seed for reproducibility using tf.random.set_seed(42), the random operations in TensorFlow, including shuffling, will produce the same results across different runs of the program as long as the operations are performed in the same order.

Here's how you can apply the seed to shuffle a tensor:

In [461]:
# Create a tensor
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Randomly shuffle the tensor along the first dimension
shuffled_tensor = tf.random.shuffle(tensor, seed=42)  # operation level random seed

# Print the original and shuffled tensors
print("Original tensor:")
print(tensor)
print("\nShuffled tensor:")
print(shuffled_tensor)

Original tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

Shuffled tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [462]:
tf.ones(shape=(10,10), dtype=tf.float32)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [463]:
tf.zeros([10,10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [464]:
A = np.arange(1, 25, dtype=np.int32)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [465]:
T = tf.constant(A, shape=(4,3,2))
T

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [466]:
T.ndim

3

In [467]:
T.shape

TensorShape([4, 3, 2])

In [468]:
T.ndim

3

In [469]:
T[3]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[19, 20],
       [21, 22],
       [23, 24]], dtype=int32)>

In [470]:
TT = tf.zeros([2, 3, 4, 5])
TT

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [471]:
2 * 3 * 4 * 5

120

In [472]:
# Get various attributes of our tensor
print("Datatype of every element: ", TT.dtype)
print("Number of dimensions (rank): ", TT.ndim)
print("Shape of tensor: ", TT.shape)
print("Elements along the 0 axis: ", TT.shape[0])
print("Elements along the last axis: ", TT.shape[-1])
print("Total number of elements in our tensor: ", tf.size(TT))
print("Total number of elements in our tensor: ", tf.size(TT).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


In [473]:
TT[: 2,: 2,: 2,: 2 ] # get first elements from tensor.

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [474]:
TT[: 1,: 1,: 1 ]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

### Basic Operations

- ```+ - / * ```

In [475]:
TTT = tf.constant([[2, 3], [4, 5]])
TTT

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [476]:
# sum
TTT = TTT + 10

In [477]:
TTT

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [14, 15]], dtype=int32)>

In [478]:
# Multiplication
TTT *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 130],
       [140, 150]], dtype=int32)>

In [479]:
tf.multiply(TTT, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 130],
       [140, 150]], dtype=int32)>

In [480]:
TTT

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [14, 15]], dtype=int32)>

In [481]:
TTT*TTT

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[144, 169],
       [196, 225]], dtype=int32)>

In [482]:
tf.matmul(TTT, TTT)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[326, 351],
       [378, 407]], dtype=int32)>

### Multiplication

![](../images/multiplication.png)


In [483]:
T1 = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
T1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [484]:
T2 = tf.constant([[3, 5], [6, 7], [1, 8]])
T2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [485]:
tf.matmul(T1, T2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [486]:
T1 @ T2 # Another way to do it is with python operator.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [487]:
T2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [488]:
tf.reshape(T2, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [489]:
E = tf.constant(np.random.randint(0, 100, size=50))

In [490]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [491]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [492]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [493]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [494]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2463>

### Variance and Standard Devitation

In [495]:
E = tf.cast(E, dtype=tf.float32)

In [496]:
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=648.9524>

In [497]:
tf.math.reduce_std(E, axis=None, keepdims=False, name=None)

<tf.Tensor: shape=(), dtype=float32, numpy=25.474545>

In [498]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=648.9524>

In [499]:
# finding for positinal minimum and maximum
tf.random.set_seed(42)
C = tf.random.uniform(shape=[50])
C

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [500]:
tf.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [501]:
C[tf.argmax(C)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [502]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [503]:
assert C[tf.argmax(C)] == tf.reduce_max(C)

In [504]:
tf.argmin(C)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [505]:
C[tf.argmin(C)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [506]:
# finding for positinal minimum and maximum
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [507]:
G.shape

TensorShape([50])

In [508]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [509]:
list_colors = [0, 1, 2]

tf.one_hot(list_colors, depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [510]:
tf.one_hot(list_colors, depth=3, on_value='On', off_value='Off')

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'On', b'Off', b'Off'],
       [b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'On']], dtype=object)>

In [511]:
H = tf.range(1, 5)
H

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [512]:
H = tf.square(H)
H = tf.cast(H, dtype=tf.float16)

In [513]:
tf.math.sqrt(H)

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1., 2., 3., 4.], dtype=float16)>

In [514]:
tf.math.log(H)

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([0.   , 1.387, 2.197, 2.773], dtype=float16)>

In [517]:
tf.config.list_physical_devices('GPU')

[]

In [515]:
tf.config.list_logical_devices

<function tensorflow.python.framework.config.list_logical_devices(device_type=None)>

In [518]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

