In [2]:
import torch

In [3]:
x = torch.zeros(3,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
x = torch.rand(4,3)
x

tensor([[0.7895, 0.2750, 0.4973],
        [0.9689, 0.3410, 0.3901],
        [0.5883, 0.2617, 0.0203],
        [0.5810, 0.3750, 0.5414]])

In [5]:
y = torch.rand(4,3)
print(x+y)

tensor([[0.8799, 0.9185, 0.7466],
        [1.9615, 0.4451, 0.6003],
        [1.5604, 1.2340, 0.3266],
        [1.4065, 0.8631, 0.7087]])


In [6]:
z = x.numpy()
z

array([[0.78952074, 0.27498198, 0.49726993],
       [0.96888775, 0.34099346, 0.39007968],
       [0.5882737 , 0.26167142, 0.0202812 ],
       [0.581019  , 0.37500948, 0.5414221 ]], dtype=float32)

In [15]:
type(z)

numpy.ndarray

In [16]:
a = torch.tensor([2.],requires_grad=True)
b = torch.tensor([4.],requires_grad=True)

In [17]:
L = 2*a**2-4*b**2

In [18]:
L.backward()

In [20]:
print(a.grad.data,b.grad.data)

tensor([8.]) tensor([-32.])
